// <auto-generated />
namespace VeracityContainerManagementAPI.DB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Containeraccessmetadata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Containeraccessmetadata));
        
        string IMigrationMetadata.Id
        {
            get { return "201801211558064_Container access metadata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
