// <auto-generated />
namespace VeracityContainerManagementAPI.DB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddOwnerIdonContainersContainerGroupsUserGroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOwnerIdonContainersContainerGroupsUserGroups));
        
        string IMigrationMetadata.Id
        {
            get { return "201801211128013_Add OwnerId on Containers ContainerGroups UserGroups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
